### ISSUE TITLE
clover conflict with wiremock

### ISSUE THREAD

**Issue by hmalewska** [bmuschko/gradle-clover-plugin#103]
When I run ```./gradlew build``` then clover is running as well and I can see that 1 test is failed because of ```com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use```

Does exist any workaround for that (probably wiremock and clover use the same port each time)?

**Comment by Alex-Vol** [comment]
I am not aware of any ports used by Clover. This is news to me.

You can have clover configured but disabled by adding this additional code in the clover closure

build.gradle
```
clover {
    enabled = project.hasProperty(cloverOn)
}
```

Then you can use `./gradlew build -PcloverOn` to run with clover enabled.
