### ISSUE TITLE
cloverAggregateReports bug with html

### ISSUE THREAD

**Issue by Lopez-i** [bmuschko/gradle-clover-plugin#105]
Hello,

i have two sub projects and a root project so i have override task : test 

```
task test(overwrite:true) {
    dependsOn ':client:test'
    dependsOn ':server:test'
    finalizedBy 'cover'
}

task cover(dependsOn: 'cloverAggregateReports')
```

Aggregated report pdf is working: 
take a look at : 
![pdf](https://image.noelshack.com/fichiers/2017/44/4/1509662602-capture-d-ecran-2017-11-02-a-23-39-39.png)

but html report is not working on root project:
![html](https://image.noelshack.com/fichiers/2017/44/4/1509662903-capture-d-ecran-2017-11-02-a-23-48-05.png)

while if i go to the client subproject report: 
![html](https://image.noelshack.com/fichiers/2017/44/4/1509663015-capture-d-ecran-2017-11-02-a-23-49-27.png)

**Comment by Alex-Vol** [comment]
In order to get an html report from the aggregate tasks you must configure clover plugin in the root project to generate html report.

```
clover {
    report {
        html = true
    }
}
```

This must be done in the root project build.gradle.

**Comment by Alex-Vol** [comment]
I believe this is as I explained and therefore not a bug. Closing.
