### ISSUE TITLE
Problems with big project 

### ISSUE THREAD

**Issue by fkluthe** [bmuschko/gradle-clover-plugin#108]
I'm trying to setup code-coverage on a big Grails project (3.1.15). I was following this description: http://guides.grails.org/grails-code-coverage/guide/index.html

First i got errors related to too large class files:
```
[groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] General error during class generation: Class file too large!
  [groovyc] 
  [groovyc] java.lang.RuntimeException: Class file too large!
  [groovyc]     at groovyjarjarasm.asm.ClassWriter.toByteArray(Unknown Source)

```

To work around this, i was using `testExcludes` and `excludes` properties in clover.gradle
It only got me so far:

```
[clover-setup] Updating existing database at '/Users/username/project/build/.clover/clover.db-test'.
Cause: invalid stream header: 02ACED00
23:11:33: Task execution finished 'cloverGenerateReport -Xms8G -Xmx12G'.
```

But no report were generated. I tried with `com.bmuschko:gradle-clover-plugin:2.1.1` and `com.bmuschko:gradle-clover-plugin:2.2.0`.

Any idea how i can make it work/narrow down the problem?

**Comment by fkluthe** [comment]
Sry i cant make the project public.

I tried out that setup with a way smaller project (same grails version/dependencies). No problem at all. Also the reports were generated within a minute. For the big project the `cloverGenerateReport` is running for hours...

I there any way how i can debug? Some `verbose` option or anything?

**Comment by Alex-Vol** [comment]
Really! `cloverGenerateReport` running for hours is fascinating. How large are your clover.db files for this? Could you post the generated clover.db files as a way to demonstrate the issue? I am not sure how much private information might be captured in the clover.db file but given that the report generator is running for hours I imaging you might be hitting a problem in Clover itself. Have you tried to ask the question in the Clover developer's forums? This seems like an issue with Clover, not with this plugin.

**Comment by fkluthe** [comment]
I revisited the issue and was not able to finish a report, always got `[groovyc] General error during class generation: Class file too large!`.. Anyway like you have written, the issue probably is not related to the plugin. Therefore i will close the issue. Thx for you time!
