### ISSUE TITLE
additionalTestDirs adds sourceSet to test sourceSet

### ISSUE THREAD

**Issue by mambon2** [bmuschko/gradle-clover-plugin#11]
We have a separate test task "integrationTest" that uses the integrationTest sourceSet.  These need to be configured differently.  that is the reason why we have a separate test task for them.

When I try to add clover instrumentation by using additionalTestDirs, the sourceSet ends up being added to the "test" sourceSet, which results in the integrationTests being executed twice.  Once by the integrationTest task and again by the test task.  The test task fails bc of lacking configuration.

We believe this to be a bug.  additionalTestDirs should add sourceSet to instrumentation w/o adding the sourceSet to the "test" sourceSet or any other sourceSet.

Thanks, Pablo Munoz

**Comment by Alex-Vol** [comment]
I merged the PR#78 and added integration tests. I believe this can be closed now as fixed.
