### ISSUE TITLE
Support for JDK 9 & 10

### ISSUE THREAD

**Issue by winstonsimon** [bmuschko/gradle-clover-plugin#119]
Looks like gradle clover plugin has no support for JDK 9 and JDK10.

unexpected token: enum
   [clover] ** Error(s) occurred and the instrumentation process can't continue.

```
classpath "com.bmuschko:gradle-clover-plugin:2.2.1"
apply plugin: "com.bmuschko.clover"
clover 'org.openclover:clover:4.2.1'

clover {
    targetPercentage = '100.000%'
    report {
        html = true
        testResultsDir = project.tasks.getByName('test').reports.junitXml.destination
        testResultsInclude = 'TEST-*.xml'
    }
    compiler {
        debug = true
    }
}
```

[clover] Processing files at 1.3 source level.

Please look into it. 

thanks!

**Comment by Alex-Vol-SV** [comment]
This is an issue with OpenClover version. Open an issue with the OpenClover project although I think this is already in their roadmap.

The plugin does not have control over this, we just provide the Gradle wrappers around the execution of the OpenClover Ant tasks behind the plugin tasks.

**Comment by winstonsimon** [comment]
Thanks Alex for responding 👍

**Comment by joferguson** [comment]
I tried using openclover 4.3.1 to get support for Java 10, but doing so I get the following error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Class not found: com.atlassian.clover.ant.taskdefs.CloverCompilerAdapter

It might be related to this: https://bitbucket.org/openclover/clover/issues/75/431-ant-javac-task-is-unable-to-find

**Comment by taylorsmithgg** [comment]
This is still broken for my builds.

**Comment by qodjf** [comment]
Why source level is 1.3 here?

**Comment by Alex-Vol-SV** [comment]
@qodjf the source level is controlled by your own Gradle source level settings. This plugin does not set the source level. The plugin is compiled at Java 8 level but will instrument up to the level supported by the OpenClover library.

**Comment by mrdanpsmith** [comment]
@Alex-Vol-SV I'm seeing the same thing with regards to the version being set at 1.3 for source that is now at version 11.

I think the problem here is that if you use a higher source version than clover supports it drops it all the way down to 1.3 rather than falling back to the next highest supported version.

Is there a way to manually set the version the instrumentation is doing using this plugin? I would like to compile the project at 11 but I don't care if it winds up being compiled down to 8 for instrumentation purposes.

**Comment by Alex-Vol-SV** [comment]
yes, see the documentation README
As long ay the source is compatible with Java8 it ought to work.

We default to the java compatibility setting but allow you to set it for the plugin

**Comment by Alex-Vol-SV** [comment]
I am going to post 2.2.5 with the sourceCompatibility override to allow this to work as long as OpenClover can indeed process the source code at Java 9 level. I do not have any handy examples to prove it works in all cases but it does indeed override the setting so the Java compiler can be at Java 11 and OpenClover can be at 9 to work.
