### ISSUE TITLE
Documentation - regex for log

### ISSUE THREAD

**Issue by freshcodemonger** [bmuschko/gradle-clover-plugin#121]
I found the regex in the example given to be matching portions of code before _LOG statements.

I think a better regex would be:

statement {
            name = 'log'
//start of line, any amount of whitespace then _LOG. minimal match before finding );            
regexp = '^[\\s]+_LOG\\..*?\\);'
        }

**Comment by Alex-Vol-SV** [comment]
Updated documentation with suggested improved regex
