### ISSUE TITLE
Control the groovyc compiler

### ISSUE THREAD

**Issue by sbglasius** [bmuschko/gradle-clover-plugin#128]
It would be nice to be able to pass options to the `groovyc` ant task in `InstrumentCodeAction` 

Pull request coming up. :slightly_smiling_face:

**Comment by Alex-Vol-SV** [comment]
Thank you very much for this pull request.

**Comment by Alex-Vol-SV** [comment]
@sbglasius I am considering adding your name in the release notes as a thank you for this contribution. Do you have any objection to me adding your name in the list of contributors for this release?

**Comment by sbglasius** [comment]
@Alex-Vol-SV  sure, why not. I don't mind :slightly_smiling_face:
