### ISSUE TITLE
2.2.2 is not yet released

### ISSUE THREAD

**Issue by gevorg** [bmuschko/gradle-clover-plugin#130]
Hi @Alex-Vol-SV ,

Looks like we have a problem with documentation, as **README.md** refers to `2.2.2` version https://github.com/bmuschko/gradle-clover-plugin#usage however that version is not yet released https://github.com/bmuschko/gradle-clover-plugin/releases

Related to https://github.com/bmuschko/gradle-clover-plugin/commit/0b56343d07c5be36f1d964392b62bb3a6015794c

Gevorg.

**Comment by Alex-Vol-SV** [comment]
It will be this weekend probably. I am preparing the docs for release.

**Comment by Alex-Vol-SV** [comment]
Started the release process. This will be available soon in the public repositories and the plugins.gradle.org location

**Comment by gevorg** [comment]
Thanks a lot!
