### ISSUE TITLE
Html report columns do not line up if a column has a format of 'longbar'

### ISSUE THREAD

**Issue by freshcodemonger** [bmuschko/gradle-clover-plugin#137]
If you have a column specification like:

```
columns {
            ncLineCount format: 'raw'
            coveredBranches format: 'longbar'
            totalBranches format: 'raw'
            coveredMethods format: '%'
            coveredStatements format: '%'
            totalStatements format: 'raw' 
        }
```
The coveredBranches longbar or any longbar format data will push the data for the column headers into different columns.  Clicking on the column header will then end up sorting the data for a different column.

**Comment by freshcodemonger** [comment]
Thanks.  I'll see about logging a bug over there.  One other thing is that the :

totalPercentageCovered format: 'raw'

is returning values like :  7,977

and I am confused how this is a percent.  Is this also a problem with openClover?

**Comment by Alex-Vol-SV** [comment]
Yes, all this plugin does is call the generate report function of OpenClover library with the specified parameters. Technically we call the Ant task with the specified parameters but you see there is no way to change the way these parameters are handled. Perhaps the OpenClover documentation on this option explains more of this value and why it is not mapping to a 0-100 indicator.
