### ISSUE TITLE
failed to create task or type clover-clean Problem: failed to create task or type clover-clean   Cause: The name is undefined.   Action: Check the spelling.   Action: Check that any custom tasks/types have been declared.   Action: Check that any <presetdef>/<macrodef> declarations have taken place.

### ISSUE THREAD

**Issue by Ankitakg** [bmuschko/gradle-clover-plugin#139]
When i am  trying to run my build.gradle with clover for a module i am  facing this error.Can anybody tell me what is this error or how to resolve it.

**Comment by Alex-Vol-SV** [comment]
Did you follow the instructions in the documentation? Specifically setting the OpenClover JAR file in the dependencies?
https://github.com/bmuschko/gradle-clover-plugin#usage

**Comment by Alex-Vol-SV** [comment]
Closing as user error since this is clearly documented and in all likelihood the result of providing an invalid OpenClover JAR dependency for the clover configuration.
