### ISSUE TITLE
Unable to compile project when clover is active

### ISSUE THREAD

**Issue by rmorrise** [bmuschko/gradle-clover-plugin#145]
See:
https://github.com/openclover/clover/issues/114

I linked a sample project in the comments for that issue to make it easy to reproduce.

**Comment by Alex-Vol-SV** [comment]
The only workaround I have for you is to move the java source files in the src/main/groovy to allow joint compilation. This is the mode we support currently.

I understand this will cause the java source to be compiled with the Groovy compiler and will not support all the latest Java features this way.

**Comment by Alex-Vol** [comment]
Closing, this is documented requirement for Groovy/Java joint compilation.
