### ISSUE TITLE
Bintray link with plugin JAR is down.

### ISSUE THREAD

**Issue by AdityaHoige** [bmuschko/gradle-clover-plugin#151]
[Bintray](https://bintray.com/bmuschko/gradle-plugins/com.bmuschko%3Agradle-clover-plugin)

**Comment by Alex-Vol** [comment]
Bintray has been sunset and no longer available. I will try to update this to use the Gradle plugin portal. The plugin in its latest version is already available from the Gradle plugin portal and can be used as any other Gradle plugin.

https://plugins.gradle.org/plugin/com.bmuschko.clover
