### ISSUE TITLE
How to apply customized source code path for code coverage?

### ISSUE THREAD

**Issue by yeskamaldev** [bmuschko/gradle-clover-plugin#152]
I have my project which is 100% in groovy having dependency to use a customized path instead of default source code directory i.e.
`src\com\appsource` and unit test code (written using SPOCK Framework) in `test\unit_test\spockframework`

Could any please tell me what are the changes I would require in my **build.gradle** file to successfully execute code coverage?
_Unable to do code coverage using IDEA plugin as well._

**Comment by Alex-Vol** [comment]
IDEA plugin is not related to the Clover plugin so I cannot answer how that works.

Regarding the Clover plugin, if your code is configured with the usual source set `main` and `test` we pick up automatically what we need from there. Are you using custom source sets other than `main` or `test` in your build.gradle?

**Comment by Alex-Vol** [comment]
No response, closing.

Examples of the required configuration exist in the plugin documents. See README.md for details.
