### ISSUE TITLE
plugin is not compatible with gradle 8.x

### ISSUE THREAD

**Issue by shanki2502** [bmuschko/gradle-clover-plugin#158]
java.outputDir was deprecated in gradle 7.6.x versions and now its removed from 8.x versions.
Current code is using this property, hence plugin is not compatible with 8.x

**Comment by Alex-Vol** [comment]
I am away for an extended time and I am not sure when I can perform the new
release ceremony. I will attempt it remotely although it is a bit complex.
I did not bring a laptop to perform work like this with me.

**Comment by Alex-Vol** [comment]
Resolved as release 3.0.6

**Comment by shanki2502** [comment]
> Resolved as release 3.0.6

3.0.6 is not available yet. Latest version on https://mvnrepository.com/artifact/com.bmuschko.clover/com.bmuschko.clover.gradle.plugin is still 3.0.3

**Comment by Alex-Vol** [comment]
The Maven Central publication happens asynchonously by the plugin portal.

See latest here

https://plugins.gradle.org/plugin/com.bmuschko.clover

**Comment by shanki2502** [comment]
> The Maven Central publication happens asynchonously by the plugin portal.
> 
> See latest here
> 
> https://plugins.gradle.org/plugin/com.bmuschko.clover

Thank you.
