### ISSUE TITLE
Clover excludes directory in test runtime classpath

### ISSUE THREAD

**Issue by koalalam** [bmuschko/gradle-clover-plugin#32]
We have a multi modules (A & B) project which the test cases in B requires test cases in A. Therefore, in B, we have the following dependency:

testCompile project(':A').sourceSets.test.output

Tests in B are working fine, however, when Clover is used, there are compilation errors complaining classes in module A are missing.

We suspected that the classes directory is excluded in the test runtime classpath by Clover:

https://github.com/bmuschko/gradle-clover-plugin/blob/master/src/main/groovy/org/gradle/api/plugins/clover/CloverPlugin.groovy

```
private FileCollection getTestRuntimeClasspath(Project project, Test testTask) {
            testTask.classpath.filter { !it.directory } + project.configurations.getByName(CONFIGURATION_NAME)
}
```

**Comment by Alex-Vol** [comment]
I agree with @phasebash regarding this use case. I am closing this issue as I believe it does not represent a reasonable use case.
