### ISSUE TITLE
maxComplexity of methodContext is not supported by plugin

### ISSUE THREAD

**Issue by agassi47** [bmuschko/gradle-clover-plugin#42]
According to https://confluence.atlassian.com/display/CLOVER/methodContext

method context has 6 attributes, 

but gradle plugin supports only name and regexp.

Please fix the line # 96 in https://github.com/bmuschko/gradle-clover-plugin/blob/master/src/main/groovy/org/gradle/api/plugins/clover/InstrumentCodeAction.groovy and method context convention

**Comment by phasebash** [comment]
A new pull request is coming this week, code is done and verified in tests.  Just need to polish up the integration tests a bit, looking for a decent set of assertions to make.

**Comment by Alex-Vol** [comment]
The new pull request never came. I reviewed the original pull request and feel strongly that the feature is worth adding. If I can manage to make a new implementation for the upcoming 2.1 release I will pull this change in.

**Comment by Alex-Vol** [comment]
Implemented feature
