### ISSUE TITLE
Test in different subproject does not add to test coverage

### ISSUE THREAD

**Issue by jjathman** [bmuschko/gradle-clover-plugin#43]
I'm not sure if I have something configured incorrectly, or if this is really a bug, any help would be appreciated.

I have a multi-project build. Let's say I have a class in projectA. There is also a test class in projectB. After the cloverAggregateReports task, the coverage report will show that the class will have 0% coverage, but the test will still show that it is run. It seems like coverage information isn't getting recorded when the test is run.

Is this something that is supposed to be supported? Thanks.

**Comment by jeeftor** [comment]
Did you ever get this working?

**Comment by imdira** [comment]
@jjathman @bmuschko  have you found any workaround this thing or do you have to create your own clover.gradle version or hack the plugin?

**Comment by jjathman** [comment]
No sorry I haven't spent any more time on it to get it working. Really the key is my last comment which is how we need to generate instrumented jars instead of what currently happens where only the project being tested is instrumented at runtime.

**Comment by imdira** [comment]
Thanks, I am trying to work out how to do that.

**Comment by Alex-Vol** [comment]
The pending milestone release of 2.1.1 will address this issue.
