### ISSUE TITLE
java is not compiled with debug info

### ISSUE THREAD

**Issue by awittig** [bmuschko/gradle-clover-plugin#51]
Hello,

The plugin currently compiles the instrumented java source _without_ debug info [`-g:vars`].

We are using Spring framework, which can rely on variable names in debug info when autowiring beans.  Adding this plugin to our build causes tests to fail, because Spring can no longer autowire many beans.

Is it possible to compile _with_ java debug info instead?

**Comment by Alex-Vol** [comment]
I believe this can be closed when I finish merging PR#53. I will look at the demo and see if it could be turned into a simple integration test to cover this issue as well.

**Comment by Alex-Vol** [comment]
Merged the PR and added integration tests
