### ISSUE TITLE
[clover-report] No coverage recordings found. No report will be generated.

### ISSUE THREAD

**Issue by srikanthsara** [bmuschko/gradle-clover-plugin#52]
Hi All,

i took small web  application(2 servlets and coressponding test classes),.. compiled with Ant script and generating clover.db , war files in target folder , generated log as shown below,...
# 

D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1>ant -f build.xml  runcoverage

Buildfile: build.xml
  [taskdef] Could not load definitions from resource cloverjunitlib.xml. It could not be found.

clean:
   [delete] Deleting directory D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\classes
   [delete] Deleting directory D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\instrumented
   [delete] Deleting directory D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\reports

instrument:
    [mkdir] Created dir: D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\instrumented
[clover-setup] Clover Version 4.0.1, built on September 01 2014 (build-932)
[clover-setup] Loaded from: C:\ant165\lib\clover.jar
[clover-setup] Clover is enabled with initstring 'D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\cloverdata\coverage.db'

init:
    [mkdir] Created dir: D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\classes
    [mkdir] Created dir: D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\reports

compile:
    [javac] Compiling 4 source files to D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\classes
   [clover] Clover Version 4.0.1, built on September 01 2014 (build-932)
   [clover] Loaded from: C:\ant165\lib\clover.jar
   [clover] Updating existing database at 'D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\cloverdata\coverage.db'.
   [clover] Processing files at 1.7 source level.
   [clover] Clover all over. Instrumented 2 files (1 package).
   [clover] Elapsed time = 0.094 secs. (21.277 files/sec, 648.936 srclines/sec)

test:

war:
      [war] Building war: D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\classes\project1.war
      [war] Warning: selected war files include a WEB-INF/web.xml which will be ignored (please use webxml attribute to war task)

report:
[clover-historypoint] Clover Version 4.0.1, built on September 01 2014 (build-932)
[clover-historypoint] Loaded from: C:\ant165\lib\clover.jar
[clover-historypoint] No coverage recordings found. No report will be generated.
[clover-report] Clover Version 4.0.1, built on September 01 2014 (build-932)
[clover-report] Loaded from: C:\ant165\lib\clover.jar
[clover-report] Loading coverage database from: 'D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\cloverdata\coverage.db'
[clover-report] Loading historical coverage data from: 'D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\cloverdata\history'
[clover-report] No coverage recordings found. No report will be generated.
[clover-report] Writing historical report to 'D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1\reports\clover.jar\history'
[clover-report] Read 0 history points.
[clover-report] No historical data found. No HTML historical report can be generated.

runcoverage:

BUILD SUCCESSFUL
Total time: 4 seconds
D:\SonarReportHTML_SVN\Clover_Tomcat_Dynamic_New\project1>

Note:Could you please help me ,what was the main issue in this process,...?

**Comment by Alex-Vol-SV** [comment]
Partial support for doing this is pending release in milestone v2.1.1

The instrumented code can be packaged in JAR within EAR/WAR files that are used in integration tests. The way this would be done is outside the scope of the Clover plugin. It would involve making the integration test pass to the embedded servlet container the system property `-Dclover.initstring=/path/to/clover.db` and making sure the `cloverAggregateDatabases` task has access to the file after the integration test is complete.
