### ISSUE TITLE
How to configure -Dclover.initstring="cloverdata\coverage.db" in tomcat server,..

### ISSUE THREAD

**Issue by srikanthsara** [bmuschko/gradle-clover-plugin#54]
hi all,
i implemented the  a web application ,deployed in tomcat and need to implement this process with clover for code coverage,..so where i need to configure -Dclover.initstring(i added this configuration -Dclover.initstring="E:\project1\cloverdata\coverage.db" %JAVA_OPTIONS% in start.bat and setenv.bat but no proper result,... )

**Comment by Alex-Vol** [comment]
Not an issue related to this plugin. Closing.
