### ISSUE TITLE
Is this plugin supported in Gradle 1.6?

### ISSUE THREAD

**Issue by sgov** [bmuschko/gradle-clover-plugin#58]
I tried it and I keep getting the message "Plugin with id 'com.bmuschko.clover' not found." while using with gradle 1.6. I tried this with gradle 2.1 and things seem fine. Also will this plugin get coverage for backend services, meaning a bunch of stood-up java services and selenium tests run on them. Please advice.

Thanks,

**Comment by bmuschko** [comment]
> I tried it and I keep getting the message "Plugin with id 'com.bmuschko.clover' not found." while using with gradle 1.6. I tried this with gradle 2.1 and things seem fine. 

How do you apply the plugin? The plugin with version 2.x is not compatible with Gradle 1.6. You'd have to go for an older version of the plugin. Please see `RELEASE_NOTES.md`.

> Also will this plugin get coverage for backend services, meaning a bunch of stood-up java services and selenium tests run on them. Please advice.

No, not possible at the moment.

**Comment by bmuschko** [comment]
I haven't heard back from you so I am going to close the issue.
