### ISSUE TITLE
Clover 4.0?

### ISSUE THREAD

**Issue by jeeftor** [bmuschko/gradle-clover-plugin#65]
The documentation points to:

    dependencies {
        clover 'com.cenqua.clover:clover:3.2.0'
    }

Is this still valid?  I thought clover was up to 4.0.6?

**Comment by bmuschko** [comment]
You can assign any Clover version you like. It's an usage example.

**Comment by Alex-Vol** [comment]
There was a minor issue with clover-optimize in the plugin which is now fixed for Clover 4.x. Also, the plugin is now building against openclover latest version.
