### ISSUE TITLE
clover.enabled not wired to do anything

### ISSUE THREAD

**Issue by szetheli** [bmuschko/gradle-clover-plugin#68]
Looking at CloverPluginConvention.groovy there is an 'enabled' that is plumbed through to InstrumentCodeAction.groovy, but then is never used.  

When I tried adding:
`clover {
    enabled = false
}`
I still get instrumented classes.  I'm interested in being able to conditionally disable clover without having to rip out all the clover references.
The particular reason I'm interested in it is because clover compiles without debug flags which makes junit output harder to read then is necessary since there are no line numbers on failed asserts.(https://github.com/bmuschko/gradle-clover-plugin/issues/51, https://github.com/bmuschko/gradle-clover-plugin/pull/57)

**Comment by mikeawatson** [comment]
We had no issue with using enabled. A value was set in a property file to read from..the only gotcha was to make sure the string was converted to boolean using the toBoolean() call.
e.g.enabled = useCloverPropertyValue.toBoolean() 
Seemed to work. We didn't see the clover output if it was set to false in property file.

**Comment by Alex-Vol-SV** [comment]
I have used enabled successfully with the provision of making sure the value assigned is a true boolean value. I think this can be classified as user error. Another choice to make it less error prone is to have the convention class normalize the input by converting the provided value to boolean internally.

**Comment by bmuschko** [comment]
@Alex-Vol-SV verified that it works as expected. Closing.
