### ISSUE TITLE
testIncludes list does not support instrumentation of spock tests

### ISSUE THREAD

**Issue by GrantSeltzer** [bmuschko/gradle-clover-plugin#69]
When I add spock tests to testIncludes list, it includes those tests as classes. Specifically i'm adding '*_/_Spec.groovy' which is how the tests are named. I believe the tests are effectively being run but show up on the class tab instead of the test tab on the bottom left of the report.

**Comment by Alex-Vol** [comment]
I am unable to reproduce the issue as stated here. In fact when I added this new integration test a few days ago I put Spock test in it with a name ending in Spec.groovy. See how I specified the testIncludes in this source example: [Spock test Ant Glob](https://github.com/bmuschko/gradle-clover-plugin/blob/master/src/integTest/projects/java-groovy-project-debug-enabled/build.gradle#L29)
