### ISSUE TITLE
[clover-setup] Attempt to copy some class files to main-bak

### ISSUE THREAD

**Issue by ShyamsunderJoshi** [bmuschko/gradle-clover-plugin#72]
Our project's gradle task - test - runs successfully if I do not have clover integration. But when I introduce clover in my buid.gradle, gradle task - test - fails. Any help is much appreciated.

Log -
:SDK:test
[clover-clean] Clover Version 3.2.0, built on October 21 2013 (build-908)
[clover-clean] Loaded from: /home/vagrant/.gradle/caches/modules-2/files-2.1/com.cenqua.clover/clover/3.2.0/e09feecf14644d92003ab037c30e483cf86b3e82/clover-3.2.0.jar
[clover-clean] Clover: Evaluation License registered to Thomson Reuters.
[clover-clean] You have 24 day(s) before your license expires.
[clover-setup] Clover Version 3.2.0, built on October 21 2013 (build-908)
[clover-setup] Loaded from: /home/vagrant/.gradle/caches/modules-2/files-2.1/com.cenqua.clover/clover/3.2.0/e09feecf14644d92003ab037c30e483cf86b3e82/clover-3.2.0.jar
[clover-setup] Clover: Evaluation License registered to Thomson Reuters.
[clover-setup] You have 24 day(s) before your license expires.
[clover-setup] Clover is enabled with initstring '/contentpipeline/projects/SDK/build/.clover/clover.db-test'
     [move] Moving 91 files to /contentpipeline/projects/SDK/build/classes
Attempt to copy /contentpipeline/projects/SDK/build/classes/main/com/thomsonreuters/contentpipeline/config/Config.class to /contentpipeline/projects/SDK/build/classes/main-bak/com/thomsonreuters/contentpipeline/config/Config.class using NIO Channels failed due to '/contentpipeline/projects/SDK/build/classes/main/com/thomsonreuters/contentpipeline/config/Config.class (No such file or directory)'.  Falling back to streams.
:SDK:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':SDK:test'.
  
  > Failed to copy /contentpipeline/projects/SDK/build/classes/main/com/thomsonreuters/contentpipeline/config/Config.class to /contentpipeline/projects/SDK/build/classes/main-bak/com/thomsonreuters/contentpipeline/config/Config.class due to /contentpipeline/projects/SDK/build/classes/main/com/thomsonreuters/contentpipeline/config/Config.class (No such file or directory)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
# 

build.gradle

apply plugin: 'groovy'
apply plugin: 'com.bmuschko.clover'

buildscript {
    repositories {
            maven {
                 jcenter()
           }
    }
    dependencies {
      classpath "com.bmuschko:gradle-clover-plugin:2.0.1"
      //classpath 'org.codehaus.groovy:groovy-all:2.4.0'
    }
}

clover {
    classesBackupDir = file("/contentpipeline/projects/SDK/build/classes/main-bak")
    report {
        html = true
    }
}

sourceSets {
  testUtil {
    groovy { srcDir 'src/test/utils' }
    compileClasspath = test.compileClasspath
  }
}

dependencies {
clover 'com.cenqua.clover:clover:3.2.0'
}

**Comment by Alex-Vol** [comment]
This is user error. In a project such as this one I would not have used the absolute path specified in this build.gradle. Instead it seems to me the correct configuration would have been this one.
```
clover {
  classesBackupDir = file("$buildDir/classes/main-bak")
}
```
