### ISSUE TITLE
Gradle 3.0 support

### ISSUE THREAD

**Issue by gubug0** [bmuschko/gradle-clover-plugin#76]
Plugin don't support gradle 3.0
In previous version of gradle, [test.testSrcDirs](https://docs.gradle.org/2.14.1/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:testSrcDirs) is deprecaed and removed in gradle 3.0.

```
apply plugin: "com.bmuschko.clover"

clover {
    licenseLocation = "###"
    compiler {
        encoding = "UTF-8"
    }
    report {
        html = true
        xml = true
    }
}
```

```
오전 11:56:04: Executing external task 'cloverGenerateReport'...
:compileJava UP-TO-DATE
:processResources
:classes
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test
[clover-clean] Clover Version 3.2.0, built on October 21 2013 (build-908)
[clover-clean] Loaded from: /Users/Naver/.gradle/caches/modules-2/files-2.1/com.cenqua.clover/clover/3.2.0/e09feecf14644d92003ab037c30e483cf86b3e82/clover-3.2.0.jar
[clover-clean] Clover: Commercial License registered to Naver Corporation.
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Could not get unknown property 'testSrcDirs' for task ':test' of type org.gradle.api.tasks.testing.Test.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.347 secs
Could not get unknown property 'testSrcDirs' for task ':test' of type org.gradle.api.tasks.testing.Test.
오전 11:56:12: External task execution finished 'cloverGenerateReport'.
```

In my case, I solved problem below:

```
test {
    ext.testSrcDirs = project.sourceSets.test.java.srcDirs
}
```

But doesn't clear I think.

THANKS

**Comment by bmuschko** [comment]
I'd be happy to release a new version if you send me a pull request that makes the plugin compatible with Gradle 3.0. As indicated by the error message, the usage of property `Test.testSrcDirs` needs to be removed from the source code. From the [Gradle Javadocs](https://docs.gradle.org/2.14.1/javadoc/org/gradle/api/tasks/testing/Test.html#getTestSrcDirs()):

> Deprecated. Support for TestNG Javadoc annotations will be removed in Gradle 3.0

**Comment by Alex-Vol-SV** [comment]
I am planning a large Gradle project migration to Gradle 3.0 and will most likely have to patch the Clover plugin for Gradle 3.0 compatibility. When I get around to this I will provide a patch for it.

Do we want to fork this to continue a support stream for gradle <= 2.14.1 and gradle >= 3.0?

**Comment by ericparton** [comment]
@Alex-Vol-SV, you might be interested to know that Atlassian recently open sourced Clover and rebranded it as Open Clover. It looks like the release of an official gradle plugin is imminent based on the information the developers posted [here](http://openclover.org/downloads).

**Comment by bmuschko** [comment]
@ericparton @Alex-Vol-SV IMHO it is still to be seen how it will play out in practice. Atlassian might have open sourced Clover but their plugin is very limited in functionality. Also I don't see any clear ownership at the moment. Please see [this Twitter conversation](https://twitter.com/bmuschko/status/854312539248881665) for more information.

**Comment by bmuschko** [comment]
@Alex-Vol-SV For this change I'd just assume that consumers will use a Gradle version >= 3.0. Let's not introduce any kind of branching logic for backward compatibility. Gradle 3.0 is already over a year old and 4.0 is going to be released soon.

**Comment by Alex-Vol-SV** [comment]
@bmuschko I was not suggesting branching logic to keep backward compatibility. More in terms of a git branch to backport any completed fixes that apply to Gradle 2.x if that is desirable.

As far as versioning I would suggest when we have a Gradle 3.0 compatible version perhaps the major version of this plugin also becomes 3.x?

**Comment by bmuschko** [comment]
@Alex-Vol-SV The 2.x in version of the plugin does not necessarily indicate Gradle 2.x compatibility. Be my guest if you want to keep things in sync on two different branches but please be aware that it will mean a significant amount of additional work. I personally would not go for it.

**Comment by Alex-Vol-SV** [comment]
I will follow you very thoughtful advice @bmuschko and will simply drop support for Gradle 2.x. I would prefer it if we released one new version that is still Gradle 2.x capable with the current set of fixes we have in the pipeline.

**Comment by bmuschko** [comment]
@Alex-Vol-SV Sure, we can do that. Let me know when you are ready.

**Comment by Alex-Vol** [comment]
I updated the build scripts and all integration tests as needed and everything is passing. No source code issues or deprecations have been encountered.

I found nowhere in the source of this plugin where Test.testSrcDirs

Is this issue a real issue for the Gradle 3.x update? It would seem that it is not related to this plugin from what I can tell so far.

**Comment by Alex-Vol** [comment]
Tested and verified with latest master. Gradle 3.5 works with all integration tests. No deprecations and no errors.
