### ISSUE TITLE
Not executing test cases in a multi-build.gradle project

### ISSUE THREAD

**Issue by ivankennethwang** [bmuschko/gradle-clover-plugin#77]
Can help me how to setup in a project structure like this?

./app/build.gradle
./app/src/main/java/Sample.java
./app/src/test/java/SampleTest.java
./build.gradle

This is my current setup and it's not executing my test cases.

Thanks in advance.

**Comment by shikharchaudhary** [comment]
If your source and tests are in the same module then clover should work fine.I am facing issues when both are in different modules.

**Comment by Alex-Vol-SV** [comment]
All my clover projects are setup in the way you are setting this one. I am noticing you did not provide a settings.gradle though. Is that an omission in your example structure? I apply the clover plugin at the root project build.gradle and at the subproject build.gradle. All tests build and provide clover coverage.

**Comment by Alex-Vol** [comment]
There is a working example in the github source code from this plugin. It is trivial but has all functional elements you would need to make yours work.

I understand that by now you probably solved this problem but I am entering this here as an answer so I can close this issue.
[Java mutliproject example](https://github.com/bmuschko/gradle-clover-plugin/tree/master/src/integTest/projects/java-multi-project)
