### ISSUE TITLE
Use TestKit for defining and executing functional tests

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-clover-plugin#80]
All tests under `integTest` should be executed with [TestKit](https://docs.gradle.org/current/userguide/test_kit.html), the built-in solution for executing functional tests with Gradle.

Goal: Avoid any custom infrastructure logic, benefit from built-in features.

What is called integration test in this project should be coined with functional test. You can find other examples on the setup of TestKit in other plugins I wrote e.g. the [Docker plugin](https://github.com/bmuschko/gradle-docker-plugin/blob/master/build.gradle#L9).

**Comment by Alex-Vol-SV** [comment]
Thank you for the suggestion @bmuschko 
I will use your Docker plugin for examples, I want to become more familiar with the TestKit in general so this is a very good excuse to do so.

**Comment by Alex-Vol-SV** [comment]
I am impressed with the clarity and structure of your tests in the Docker plugin @bmuschko - I think I will borrow much of your build logic when I get to this task. I am excited at the opportunity to make this change.
