### ISSUE TITLE
Upgrade to project to use latest Gradle version

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-clover-plugin#81]
- Upgrade to latest Gradle version to benefit from new features and performance improvements
- Make changes to build code as required
- Fix all deprecations

**Comment by Alex-Vol** [comment]
I tried building with Gradle 3.5 and everything just worked. This may be completed after all. I will run with this for a bit and try it on a project to see if anything comes up.

**Comment by Alex-Vol** [comment]
Tested and verified with latest master. Gradle 3.5 works with all integration tests. No deprecations and no errors.
