### ISSUE TITLE
Use different CI solution

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-clover-plugin#82]
[SnapCI is going to shut down](https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/) in August 2017. Find a different, free CI product optimally with support for modeling pipelines. So far I used [Snap CI to continuous build this project](https://app.snap-ci.com/bmuschko/gradle-clover-plugin/branch/master).

**Comment by Alex-Vol-SV** [comment]
I did some research on this and TravisCI seems like a candidate. I have seen it used effectively on other open source projects. It will be a bit of a learning for me but I am open to do that. What do you suggest as the next steps @bmuschko ? 

Perhaps I sign up for a free account and try it out is what I think.

**Comment by Alex-Vol-SV** [comment]
I noticed that you have a Gitlab CI configuration in your docker plugin @bmuschko - is Gitlab CI a good choice? It seems capable enough to me. Although there is the configuration Yaml in the docker plugin repository the Snap CI is still in use. Are there issues you have encountered with Gitlab CI?

**Comment by bmuschko** [comment]
Travis CI will probably work. Unfortunately, Travis doesn't allow for declaring pipelines and manual steps for deployment/publishing. Gitlab CI does provide it. I played around with it in the Docker plugin but there are also some shortcoming e.g. I didn't find a good way to let somebody else view the pipeline, there's no good way to expose a badge etc. The Docker plugin is mostly maintained by somebody else now so I'll leave it up to them to iron out the details.

**Comment by bmuschko** [comment]
For now I set up Travis CI and added a build badge on the README file. We can look into other options as needed.

**Comment by Alex-Vol** [comment]
Thanks @bmuschko for putting this on Travis. I have not yet found an alternative that does as good a job as SnapCI did. The few days of interaction I had with SnapCI and the new Travis build give me a good idea why you were looking for something with the features provided by SnapCI.
