### ISSUE TITLE
Update plugin to support openclover and clover 4.x

### ISSUE THREAD

**Issue by Alex-Vol-SV** [bmuschko/gradle-clover-plugin#83]
The main difference in the 3.x and 4.x clover is that the cloverjunitlib.xml Ant task definition has been merged into cloverlib.xml. Fixing this for clover 3 and clover 4 is actually fairly easy by detecting the version of clover in the clover configuration dependency and adjusting the ant.taskdef() call.

**Comment by Alex-Vol** [comment]
Fixed. Now we build and test with the new Open Clover 4.2.0

Also updated the build framework to Gradle 2.14.1
