### ISSUE TITLE
Grails 3 project fails to find Groovyc class

### ISSUE THREAD

**Issue by Alex-Vol** [bmuschko/gradle-clover-plugin#89]
Similar to the older issue #59 a Grails 3 project requires the addition of groovy compile dependency to compile Groovy tests.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> taskdef class org.codehaus.groovy.ant.Groovyc cannot be found
```

Current workaround is:
```
compile 'org.codehaus.groovy:groovy-all:2.4.7'
```
or
```
provided 'org.codehaus.groovy:groovy-all:2.4.7'
```

where 2.4.7 is an appropriate groovy version for your project and `provided` has to be a correct and available configuration scope for your project. I believe Grails defines a `provided` configuration scope.

**Comment by Alex-Vol-SV** [comment]
The use of Groovy in this plugin is designed to work with Groovy in the compile classpath. I can attempt adding Gradle internal Groovy libraries in the classpath when invoking the Groovyc compiler but I am concerned this might inject improper dependency to Groovy in the code under test.

The current workaround to add groovy-all in `compile` or `provided` configuration may be an acceptable one if there are no other options.
