### ISSUE TITLE
Problems with Static Compilation in a Grails MultiProject Build

### ISSUE THREAD

**Issue by jlstrater** [bmuschko/gradle-clover-plugin#95]
I have been trying to add this Gradle Clover Plugin to our Grails project.  It's setup as a multi-project build so I had to tweak it a bit from @sdelamo 's [Grails Guide](http://guides.grails.org/grails-code-coverage/guide/index.html).

Our clover.gradle file looks like this:

```
apply plugin: 'com.bmuschko.clover'

dependencies {
    clover 'org.openclover:clover:4.2.0'
}

ext {
    filesToExclude = ['**/Application.groovy',
                '**/BootStrap.groovy',
                '**/UrlMappings.groovy',
                '**/*GrailsPlugin.groovy',
                '**/*Mock.groovy',

                '**/*.java',
    ]
}

clover {
    licenseLocation = File.createTempFile('clover', '.license').absolutePath

    excludes = filesToExclude

    testIncludes = ['**/*Spec.groovy']

    report {
        html = true
        xml = true
    }
}

subprojects {
    apply plugin: 'com.bmuschko.clover'

    clover {
        licenseLocation = File.createTempFile('clover', '.license').absolutePath

        excludes = filesToExclude

        testIncludes = ['**/*Spec.groovy']

        report {
            xml = true
        }
    }

    dependencies {
        clover 'org.openclover:clover:4.2.0'
    }
}
```

As written, the build script applies the clover plugin which attempts to recompile the project.  It does so using static type checking which our project does not support.

Am I missing a configuration option or is this an issue?

**Comment by Alex-Vol** [comment]
The plugin invokes the Groovyc Ant task on the main source set and test source set by attaching an InstrumentCodeAction to the Test tasks. We do not specify any options to the Groovyc compiler that would alter the way it gets the compilation done. I am not sure why you have this issue or what I can do to alter the compilation. I would need an example to figure this out.

Can you produce a minimal Grails project that exhibits this behavior?

**Comment by Alex-Vol** [comment]
Can you show the kinds of error output you get from your project with Clover enabled @jlstrater ? I am curious how this failure manifests itself. Wondering if you are hitting a limitation of Clover itself with respect to Groovy instrumentation.

**Comment by sdelamo** [comment]
maybe completely unrelated @jlstrater but if I was getting errors if using @GrailsCompileStatic annotation.

**Comment by jlstrater** [comment]
Thanks, everyone. I'm going to try to create an example project (hopefully over the weekend) to see if I can replicate the issue or if it's something for this specific project.

**Comment by jlstrater** [comment]
Ok. So it looks like this was an issue with Clover itself as reported in https://jira.atlassian.com/browse/CLOV-1863 The files that were failing were regular groovy files (not in the grails-app) specifically marked with `@CompileStatic` and were failing exactly as described.

**Comment by Alex-Vol** [comment]
Thank you for reporting on the resolution of this problem @jlstrater it helps raise awareness of the issue.

**Comment by abcfy2** [comment]
I have the same issue. When the domain class with `@GrailsCompileStatus` annotation will see this error.

**Comment by Alex-Vol-SV** [comment]
Vote for the https://jira.atlassian.com/browse/CLOV-1863 to have it fixed. It is still open.
