### ISSUE TITLE
Automate release process following gradle-docker-plugin scheme

### ISSUE THREAD

**Issue by Alex-Vol** [bmuschko/gradle-clover-plugin#96]
@bmuschko I read the solution you and the team of contributors came up with at https://github.com/bmuschko/gradle-docker-plugin/pull/402 and I find it is a fitting solution to use for this plugin. If it is OK with you I would like to make the changes to this plugin to follow the same procedure for releases.

Let me know if that is a solution you approve. I will make a PR with the solution sometime next week.

**Comment by bmuschko** [comment]
That approach sounds good to me. I didn't propose it yet as I wanted to see first whether we run into any issues with the Docker plugin. Looks to me as it works smoothly now. Feel free to adapt the approach. Then you can publish releases yourself. :-)

**Comment by Alex-Vol** [comment]
OK, I will work on both and see about getting TestKit functional tests in the process.

Yes, I opened an issue for Gradle 4 compatibility which has been identified by a user.
