### ISSUE TITLE
compileOnly dependencies aren't properly added to classpath when using clover

### ISSUE THREAD

**Issue by fbazbo** [bmuschko/gradle-clover-plugin#99]
I had a working project that integrated clover and notice that when I change some of the dependencies to compileOnly, the compile fails.  Removing the clover integration or reverting the compileOnly will make it work, but it would be nice to have both rather than one or the other!

**Comment by Alex-Vol** [comment]
compileOnly is a Gradle 4.x feature. We have not made this compatible with the new Gradle 4.x features yet.

**Comment by fbazbo** [comment]
OK, thanks... it was driving me crazy since some projects were working and other's weren't...

**Comment by Alex-Vol** [comment]
I will try to unravel the new way dependencies work and see how it intersects with this plugin. Perhaps all I need to do is detect the new configurations and if present add them to the classpath. We use the Ant tasks from Clover to compile so the classpath needs to be configured explicitly.

**Comment by fbazbo** [comment]
According to this -
https://blog.gradle.org/introducing-compile-only-dependencies, you should
now be using compileClasspath property for the sourceset instead of the
compile property to get all the relevant classpath references...

**Comment by thetric** [comment]
@fbazbo The new version 2.1.3 works with Gradle 4.1

@Alex-Vol-SV Thank you for your fix! I was facing the same problem. When will the latest version be available on plugins.gradle.org?

**Comment by Alex-Vol** [comment]
I requested from Ben Muschko to publish the new version on Bintray and the plugins.gradle.org. He is busy so it may take a day to happen. Thanks for the feedback.

There is still some work to be fully 4.x compatible. In order for that to happen I may have to break compatibility with earlier versions though. I will probably bump the major version of the plugin when this happens.
